# Generated by Django 4.1.7 on 2023-04-09 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Provider',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.customer')),
            ],
        ),
    ]
