# Generated by Django 4.1.7 on 2023-04-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_rename_seller_provider_alter_contactus_mobile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='seeker',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
