# Generated by Django 4.1.7 on 2023-04-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0011_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='gender',
        ),
    ]
