# Generated by Django 4.1.7 on 2023-04-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0013_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
