# Generated by Django 4.1.7 on 2023-05-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0014_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
