# Generated by Django 4.1.7 on 2023-05-02 16:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0016_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.TextField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
