# Generated by Django 4.1.7 on 2023-05-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0018_remove_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
